### ISSUE TITLE
Python2 support [Was: Failed to runserver due to non-ascii character]

### ISSUE THREAD

**Issue by opi** [gordon-/atable#1]
After installing requirements, I try to launch a local server to run the app with the following command : `python manage.py runserver 8080`

Here is the traceback : 

```
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 303, in execute
    settings.INSTALLED_APPS
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 48, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 44, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 92, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/path/to/atable/atable/settings.py", line 128
SyntaxError: Non-ASCII character '\xc5' in file /path/to/atable/atable/settings.py on line 129, but no encoding declared; see http://www.python.org/peps/pep-0263.html for details
```

System information: Regular ubuntu 14.04.2

**Comment by vegaelle** [comment]
I didn’t write any documentation yet (nor any test), but this project is Python3-only. Your error comes from Python2 string management.

Py2 support shouldn’t be a major problem, but it seems to be a minor issue right now.
