### ISSUE TITLE
Cannot load test data

### ISSUE THREAD

**Issue by progval** [gordon-/atable#17]
```
$ ./manage.py loaddata tests
[…]

Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/progval/.local/lib/python3.4/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/home/progval/.local/lib/python3.4/site-packages/django/core/management/__init__.py", line 330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/progval/.local/lib/python3.4/site-packages/django/core/management/base.py", line 390, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/progval/.local/lib/python3.4/site-packages/django/core/management/base.py", line 441, in execute
    output = self.handle(*args, **options)
  File "/home/progval/.local/lib/python3.4/site-packages/django/core/management/commands/loaddata.py", line 60, in handle
    self.loaddata(fixture_labels)
  File "/home/progval/.local/lib/python3.4/site-packages/django/core/management/commands/loaddata.py", line 90, in loaddata
    self.load_label(fixture_label)
  File "/home/progval/.local/lib/python3.4/site-packages/django/core/management/commands/loaddata.py", line 147, in load_label
    obj.save(using=self.using)
  File "/home/progval/.local/lib/python3.4/site-packages/django/core/serializers/base.py", line 176, in save
    setattr(self.object, accessor_name, object_list)
  File "/home/progval/.local/lib/python3.4/site-packages/django/db/models/fields/related.py", line 1252, in __set__
    "intermediary model.  Use %s.%s's Manager instead." % (opts.app_label, opts.object_name)
AttributeError: Problem installing fixture '/home/progval/dev/atable/atable/recipes/fixtures/tests.yaml': Cannot set values on a ManyToManyField which specifies an intermediary model.  Use recipes.ParentRecipe's Manager instead.
```

**Comment by vegaelle** [comment]
Current fixtures were not migrated for current models. I may have up-to-date test data, but feel free to import these in an old database migration and then migrate to HEAD and update fixtures file

**Comment by progval** [comment]
The problem fixed itself. It looks like migrations are now run after the fixtures import.

**Comment by progval** [comment]
nevermind
